name: Linters

on:
  pull_request:
    branches:
      - '*'

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.1.x

      - name: Install dependencies
        run: |
          gem install --no-document rubocop -v '>= 1.0, < 2.0'
          [ -f .rubocop.yml ] || wget https://raw.githubusercontent.com/microverseinc/linters-config/master/ror/.rubocop.yml

      - name: Rubocop Check
        run: rubocop --color

  eslint:
    name: ESLint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install ESLint dependencies
        run: |
          npm install --save-dev eslint eslint-config-airbnb-base eslint-plugin-import
          npm install --save-dev eslint-config-airbnb eslint-plugin-jsx-a11y eslint-plugin-react eslint-plugin-react-hooks
          [ -f .eslintrc.json ] || wget https://raw.githubusercontent.com/microverseinc/linters-config/master/react-redux/.eslintrc.json

      - name: ESLint Check
        run: npx eslint "**/*.{js,jsx}"

  stylelint:
    name: StyleLint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install StyleLint dependencies
        run: |
          npm install --save-dev stylelint stylelint-scss stylelint-config-standard stylelint-csstree-validator
          [ -f .stylelintrc.json ] || wget https://raw.githubusercontent.com/microverseinc/linters-config/master/react-redux/.stylelintrc.json

      - name: StyleLint Check
        run: npx stylelint "**/*.{css,scss}"
